version: '3.8'

services:
  db_postgres:
    image: postgres:14.1-alpine
    container_name: db_postgres
    restart: 'always'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  db_mongo:
    image: mongo:6.0
    container_name: db_mongo
    restart: 'always'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db

  web:
    build:
      context: .
    container_name: app
    restart: 'always'
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      db_postgres:
        condition: service_healthy
      db_mongo:
        condition: service_healthy

  frontend:
    image: nginx:alpine
    container_name: front
    restart: 'always'
    volumes:
      - ./front:/usr/share/nginx/html
    ports:
      - "8048:80"
    depends_on:
      - web
