version: '3.8'

services:
  db_postgres:
    image: postgres:14.1-alpine
    container_name: db_postgres
    restart: 'always'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  db_mongo:
    image: mongo:6.0
    container_name: db_mongo
    restart: 'always'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db

  web:
    build:
      context: .
    container_name: app
    restart: 'always'
    command: >
      sh -c "wait-for-it db_postgres:5432 -- wait-for-it db_mongo:27017 -- python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db_postgres
      - db_mongo

  frontend:
    image: nginx:alpine
    container_name: front
    restart: 'always'
    volumes:
      - ./front:/usr/share/nginx/html
    ports:
      - "8048:80"
    depends_on:
      - web
