# Generated by Django 3.1.12 on 2024-12-15 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postgresql_app', '0002_auto_20241215_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='car_price',
        ),
        migrations.RemoveField(
            model_name='client',
            name='car_type',
        ),
        migrations.AddField(
            model_name='client',
            name='car_bought',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='postgresql_app.car'),
        ),
    ]
