# Generated by Django 3.1.12 on 2024-12-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgresql_app', '0003_auto_20241215_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='car_bought',
        ),
    ]
