# Generated by Django 3.1.12 on 2024-12-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresql_app', '0005_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
