# Generated by Django 3.1.12 on 2024-12-15 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mongodb_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='id',
            new_name='_id',
        ),
    ]
