# Generated by Django 3.1.12 on 2024-12-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongodb_app', '0002_auto_20241215_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_id',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
